### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by SISheogorath** [dariko/httpd-rproxy-ldap#2]
In order to be a useful repository it is needed to have a license.

As by default no one is allowed to copy this source code (besides GitHub).

It would be nice if you use MIT or GPL License.

For more information see: 
https://choosealicense.com/ 
and
https://www.youtube.com/watch?v=cJIi-hIlCQM

**Comment by dariko** [comment]
Now this repository is released under [GPLv3](https://github.com/dariko/httpd-rproxy-ldap/blob/master/LICENSE) (ffa7785a9a74db6455b0639e145e72931e20d214)
thanks for the links :)
